stages:
  - test
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: test/**

code_quality:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never

lint-deno:
 image: hayd/ubuntu-deno:1.9.2
 stage: test
 tags:
   - docker
 script:
   - cd deno
   - deno lint --unstable

test-deno:
  coverage: '/(\d+\.\d+\%)/'
  image: hayd/ubuntu-deno:1.9.2
  stage: test
  tags:
    - docker
  script:
    - cd deno
    - deno test --coverage=coverage --unstable
    - deno coverage --unstable coverage
